### PR TITLE
- Added NSData category with similar functionality and unit tests

### PR DESCRIPTION
**Pull request by anivaros**
- Added NSData category with similar functionality
- Added unit tests to check all works fine

### CODE REVIEW

**Review by hypercrypt — APPROVED** [review]

**Comment by hypercrypt** [comment]
Thanks for this - looks great

**Comment by anivaros** [comment]
Could you please create new pod version with this changes? 🙏

**Comment by hypercrypt** [comment]
I created a version 1.3. Haven't done this in ages, anything else I need to do?

**Comment by anivaros** [comment]
Docs says that you should:
1. Bumb version in podspec and commit
2. Add tag
3. Run `pod trunk push NAME.podspec` in terminal

**Comment by hypercrypt** [comment]
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  NSString-Hashes (1.3.1) successfully published
 📅  February 25th, 12:04
 🌎  https://cocoapods.org/pods/NSString-Hashes
 👍  Tell your friends!
--------------------------------------------------------------------------------

**Comment by hypercrypt** [comment]
Thanks for this PR and your help

**Comment by anivaros** [comment]
Thank you very much!

**Pull request merged**
